package permissions.dispatcher.processor.util

const val FILE_COMMENT = "This file was generated by PermissionsDispatcher. Do not modify!"
const val GEN_CLASS_SUFFIX = "PermissionsDispatcher"
const val GEN_REQUEST_CODE_PREFIX = "REQUEST_"
const val GEN_PERMISSION_PREFIX = "PERMISSION_"
const val GEN_PENDING_PREFIX = "PENDING_"
const val GEN_WITH_PERMISSION_CHECK_SUFFIX = "WithPermissionCheck"
const val GEN_PERMISSION_REQUEST_SUFFIX = "PermissionRequest"
