package permissions.dispatcher.processor.util

val FILE_COMMENT = "This file was generated by PermissionsDispatcher. Do not modify!"
val GEN_CLASS_SUFFIX = "PermissionsDispatcher"
val GEN_REQUEST_CODE_PREFIX = "REQUEST_"
val GEN_PERMISSION_PREFIX = "PERMISSION_"
val GEN_PENDING_PREFIX = "PENDING_"
val GEN_WITH_PERMISSION_CHECK_SUFFIX = "WithPermissionCheck"
val GEN_PERMISSION_REQUEST_SUFFIX = "PermissionRequest"
