package permissions.dispatcher.processor.util

public val FILE_COMMENT: String = "This file was generated by PermissionsDispatcher. Do not modify!"
public val GEN_CLASS_SUFFIX: String = "PermissionsDispatcher"
public val GEN_REQUESTCODE_PREFIX: String = "REQUEST_"
public val GEN_PERMISSION_PREFIX: String = "PERMISSION_"
public val GEN_WITHCHECK_SUFFIX: String = "WithCheck"
public val GEN_PERMISSIONREQUEST_SUFFIX: String = "PermissionRequest"
